name: Build

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  setup-node:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-node-modules.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'

  build:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        if: needs.setup-node.outputs.cache-hit != 'true'
        run: npm install

      - name: Run Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Notify Build Success
        run: echo "Build completed successfully."
        if: ${{ success() }}

      - name: Notify Build Failure
        run: echo "Build failed. Please check the logs for more details."
        if: ${{ failure() }}

  conditional-deployment:
    needs: build
    if: github.ref == 'refs/heads/main' && needs.build.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Notify Conditional Deployment Start
        run: echo "Starting conditional deployment based on successful build."

  notifications:
    if: always()
    needs: [build, conditional-deployment]
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification on Success
        if: ${{ needs.build.result == 'success' && needs.conditional-deployment.result == 'success' }}
        run: curl -X POST -H 'Content-type: application/json' --data '{"text":"Build and deployment successful for GeneraTeam."}' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Notification on Failure
        if: ${{ needs.build.result == 'failure' || needs.conditional-deployment.result == 'failure' }}
        run: curl -X POST -H 'Content-type: application/json' --data '{"text":"Build or deployment failed for GeneraTeam."}' ${{ secrets.SLACK_WEBHOOK_URL }}