name: Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Notify Build Success
        run: echo "Build completed successfully."
        if: ${{ success() }}

      - name: Notify Build Failure
        run: echo "Build failed. Please check the logs for more details."
        if: ${{ failure() }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Notify Test Success
        run: echo "Tests completed successfully."
        if: ${{ success() }}

      - name: Notify Test Failure
        run: echo "Tests failed. Please check the logs for more details."
        if: ${{ failure() }}

  deploy:
    needs: test
    if: ${{ github.ref == 'refs/heads/main' && needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to Production
        run: echo "Deploying to production server."
        # {Add your deployment script or command here}

      - name: Notify Deployment Success
        run: echo "Deployment completed successfully."

      - name: Notify Deployment Failure
        if: ${{ failure() }}
        run: echo "Deployment failed. Please check the logs for more details."