name: Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Notify Build Success
        run: echo "Build completed successfully."
        if: ${{ success() }}

      - name: Notify Build Failure
        run: echo "Build failed. Please check the logs for more details."
        if: ${{ failure() }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Notify Test Success
        run: echo "Tests completed successfully."
        if: ${{ success() }}

      - name: Notify Test Failure
        run: echo "Tests failed. Please check the logs for more details."
        if: ${{ failure() }}

  deploy:
    needs: test
    if: ${{ github.ref == 'refs/heads/main' && needs.test.result == 'success' && env.ENABLE_CI_CD == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to Production
        run: echo "Deploying to production server."
        # Deployment script or command should be added here based on the project's deployment strategy

      - name: Notify Deployment Success
        run: 
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment completed successfully for GeneraTeam."}' ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ success() }}

      - name: Notify Deployment Failure
        run: curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment failed for GeneraTeam. Please check the logs for more details."}' ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() }}